import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-hero-pattern bg-cover bg-opacity-25 bg-fixed">
      <body className={`${inter.className} px-4 md:px-16 2xl:max-w-screen-2xl mx-auto overflow-y-scroll`}>{children}</body>
    </html>
  );
}
